name: Publish

on:
  push:
    tags:
      - "v0.0.0"

permissions:
  contents: read
  id-token: write   # REQUIRED for PyPI Trusted Publishing (OIDC)

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build distributions
        run: |
          python -m pip install --upgrade pip build
          python -m build   # creates dist/*.tar.gz and *.whl

      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
